[WIP] Adding Great Expectations operator
superconductive/airflow pull request #1
Opened 2020-10-23 00:40 UTC by spbail

Making a PR against our fork so we can have an internal review first.

2020-10-26 15:17 UTC, jcampbell requested changes
<3!

2020-10-26 15:17 UTC, jcampbell commented on airflow/providers/greatexpectations/operators/greatexpectations.py
> +                 run_id=None,
Update to the new run_name; that will then be paired with the run time automatically.

```suggestion
                 run_name=None,
```

2020-10-26 15:17 UTC, jcampbell commented on airflow/providers/greatexpectations/operators/greatexpectations.py
> +            DataContext object expectation_suite_name: The name of the Expectation Suite to use for validation
I think formatting got kerfuffled

2020-10-26 15:17 UTC, jcampbell commented on airflow/providers/greatexpectations/operators/greatexpectations.py
> +        self.run_id = run_id
```suggestion
        self.run_name = run_name
```

2020-10-26 15:17 UTC, jcampbell commented on airflow/providers/greatexpectations/operators/greatexpectations.py
> +            run_id=self.run_id
```suggestion
            run_name=self.run_name
```

2020-10-28 18:22 UTC, eugmandel reviewed
Looks good to me. Agree with @jcampbell 's run_name comment. I went over the code, but I cannot try it yet, because pip-installing the Airflow fork hangs. I'll try resolving it.

2020-11-02 15:40 UTC, spbail reviewed
Changed the run_id to run_name and fixed the docstrings

2020-11-02 15:40 UTC, spbail commented on airflow/providers/greatexpectations/operators/greatexpectations.py
> +            DataContext object expectation_suite_name: The name of the Expectation Suite to use for validation
Ah yeah, fixed it.

2020-11-02 15:57 UTC, merged